### ISSUE TITLE
Can't compile framework in Swift project

### ISSUE THREAD

**Issue by Arideno** [flashphoner/wcs-ios-sdk-samples#5]
Hi, I have added FPWCSApi2.framework to my workspace, trying to compile, but getting these errors:
`Undefined symbol: _RTCInitializeSSL
Undefined symbol: _OBJC_CLASS_$_RTCVideoFrame
Undefined symbol: _OBJC_METACLASS_$_RTCVideoCapturer
Undefined symbol: _OBJC_CLASS_$_RTCVideoCapturer
Undefined symbol: _OBJC_CLASS_$_SRWebSocket
Undefined symbol: _OBJC_CLASS_$_RTCSessionDescription
Undefined symbol: _OBJC_CLASS_$_JSONModel
Undefined symbol: _OBJC_CLASS_$_RTCCameraVideoCapturer
Undefined symbol: _RTCFileName
Undefined symbol: _OBJC_CLASS_$_RTCPeerConnectionFactory
Undefined symbol: _OBJC_CLASS_$_RTCMediaConstraints
Undefined symbol: _RTCLogEx
Undefined symbol: _OBJC_CLASS_$_RTCCVPixelBuffer
Undefined symbol: _OBJC_CLASS_$_RTCConfiguration
Undefined symbol: _OBJC_CLASS_$_RTCDefaultVideoDecoderFactory
Undefined symbol: _OBJC_CLASS_$_RTCDefaultVideoEncoderFactory
Undefined symbol: _OBJC_METACLASS_$_JSONModel`
Can you please help?!

**Comment by flashphoner** [comment]
Good day.
Please check if you run `pod install` in project folder. The dependencied should be installed from CocoaPods.
Please also check if you prepared brigde headers to integrate iOS SDK to Swift project.
Now we're working on Swift iOS SDK wrapper in internal ticket WCS-2853. Please check [release notes](https://docs.flashphoner.com/display/IOSSDK2EN/iOS+SDK+2.6+release+notes) to know when it will be released.

**Comment by flashphoner** [comment]
Since build 2.6.19, iOS SDK includes two frameworks: Objective C and Swift
Please review Swift framework examples description here and source code here
