### ISSUE TITLE
Mute Audio' and 'Mute Video' are not available in WCSStream in FPWCSApi2Swift.framework

### ISSUE THREAD

**Issue by ElizavetaIOS** [flashphoner/wcs-ios-sdk-samples#6]
Hello, Mute Audio' and 'Mute Video' are not available in WCSStream in FPWCSApi2Swift.framework

**Comment by flashphoner** [comment]
Good day.
The methods `WCSStream.muteAudio()` and `WCSStream.muteVideo()` are declared in Swift framework headers (see `FPWCSApi2Swift.xcframework\ios-arm64_armv7\FPWCSApi2Swift.framework\Headers\FPWCSApi2Stream.h` file) and can be used in code.
Please try to modify [Two Way Streaming example code](https://github.com/flashphoner/wcs-ios-sdk-samples/blob/5b4dee191cd3a4a8d8bd73eea3b1c693d5a4b586/Swift/TwoWayStreaming/ViewController.swift#L299) like this:
```
    fileprivate func onPublishing(_ stream:FPWCSApi2Stream) {
        publishButton.setTitle("STOP", for:.normal);
        changeViewState(publishButton, true);
        stream.muteAudio();
    }
```
The example is building successfully with latest iOS SDK build [2.6.27](https://flashphoner.com/downloads/builds/flashphoner_client/wcs-ios-sdk/2.6/WCS-iOS-SDK-2.6.27.tar.gz)

**Comment by ElizavetaIOS** [comment]
Thank you!
