### ISSUE TITLE
please rebuild for xcode 13

### ISSUE THREAD

**Issue by emartinson** [flashphoner/wcs-ios-sdk-samples#7]
Hi! I'm trying to integrate SDK v2.6.73 into my demo project but can't build it because of error:

`Failed to build module 'FPWCSApi2Swift'; this SDK is not supported by the compiler (the SDK is built with 'Apple Swift version 5.3.2 (swiftlang-1200.0.45 clang-1200.0.32.28)', while this compiler is 'Apple Swift version 5.5.2 (swiftlang-1300.0.47.5 clang-1300.0.29.30)'). Please select a toolchain which matches the SDK.`

I was unable to find `FPWCSApi2` repo on github and had to report issue here.

Can you please rebuild framework using latest toolkit (xcode 13.2.1 for today) ?

**Env:**
MacOS 21.1 Monterey
XCode 13.2.1
Swift 5

**Comment by flashphoner** [comment]
According to [this post](https://developer.apple.com/forums/thread/697110?answerId=699301022#699301022), it should be enough to build framework as XCFramework. This is already done. Please check if you follow [this integration manual](https://docs.flashphoner.com/display/IOSSDK2EN/iOS+SDK+Swift+framework+integration). Also, the examples build target is set to iOS 9 by default, please set it to 12 or higher.

**Comment by flashphoner** [comment]
We cannot reproduce this problem while building example applications by [this doc](https://docs.flashphoner.com/display/IOSSDK2EN/How+to+build+examples+using+Xcode+10+and+higher) in Xcode 13.2.1

**Comment by emartinson** [comment]
Ok, thank you. I've managed to resolve this.
